import Head from "next/head";
import { AiOutlineMail, AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Image from "next/image";
import avatar from "../public/Kolesnikova.jpg";
import Tabs from "./tabs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Oleksandra Kolesnikova Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="px-8 dark:bg-gray-900 md:px-16 lg:px-40">
        <section>
          <nav className="py-8 md:px-2 flex justify-between">
            <h1 className="font-bold uppercase text-md tracking-wide">
              <span className="hidden sm:inline">Developer</span> Portfolio
            </h1>
            <ul className="flex justify content-between gap-8 font-semibold">
              <li className="mt-1 cursor-pointer">
                <BsFillMoonStarsFill />
              </li>
              <li>Skills</li>
              <li>Works</li>
              <li>
                <a
                  className="box-border px-2 py-1 border-2 rounded border-fuchsia-700 text-white bg-fuchsia-700 hover:text-fuchsia-700 hover:bg-white"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
        </section>
        <section className="h-fit mt-4">
          <div className="text-center p-6">
            <h2 className="font-bold text-4xl md:text-5xl text-fuchsia-700 tracking-wide py-2">
              Oleksandra Kolesnikova
            </h2>
            <h3 className="font-semibold text-2xl md:text-3xl py-2">
              Frontend Developer and Web Content Designer
            </h3>
          </div>
          <div className="text-4xl text-gray-600 flex justify-center gap-16 py-3">
            <AiFillLinkedin />
            <AiFillGithub />
            <AiOutlineMail />
          </div>
          <div className="relative rounded-full w-72 h-72 mx-auto mt-10 mb-12 overflow-hidden">
            <Image src={avatar} alt="Oleksandra Kolesnikova" />
          </div>
        </section>
        <Tabs />
        <section>
          <div className="text-center">
            <h3 className="font-semibold text-2xl md:text-3xl py-2">
              Have a Look at my Works
            </h3>
          </div>
        </section>
      </main>
    </>
  );
}
